### ISSUE TITLE
option_{separators,prefix}_{long,short} should be pattern-specific, not cli-specific

### ISSUE THREAD

**Issue by moon-chilled** [GamePad64/openautocomplete#1]
There could be multiple option patterns that are dispatched differently.  For instance, gnu dd takes most params as `key=value` (prefix=`[""]`, `separator=["="]`).  But it also accepts `--help` and `--version` (prefix=`["--"]`, separator=`[]`)

**Comment by GamePad64** [comment]
`git`, `dd`, `tar`, `apt`, `format` (from Windows 95 and Windows 10), `dir` (win10), `ls` and `naval_fate` (a fake command from `docopt` examples), `Get-ChildItem` (PS) were, in fact "model" commands, because they have some quirks in their command line argument handling.
- `git` has a very large CLI with some non-standard argument syntax. For example, `git diff [<options>] <commit>...<commit> [--] [<path>...]`, that has three points between diff revisions. Also, we will have to display git revisions with commit messages here, so delegated enumerations will be useful.
- `dd` has `key=value` options
- `tar` has an [old option style](https://www.gnu.org/software/tar/manual/html_section/tar_21.html#SEC38)
- `apt` should have custom delegated enumerations for installing-removing packages. Also, it has options using `-o "Option=Value"` syntax.
- `format` has slashes as prefixes, and a semicolon as an argument separator. Also, it has options after the arguments.
- `dir` has a strange option and sorting parameters (separated using a semicolon)
- `ls` -- normal Unix-style command
- `naval_fate` is pretty normal command, too. And it is short, which is useful for development and testing.
- `Get-ChildItem` (as pretty much other PS commands) has capitalized options with a single dash prefix.

As for `dd` -- I totally agree, that separators/prefixes should be pattern-specific, and I will address this in the next revision.
